### ISSUE TITLE
Make csig:Signer optional in Implementation Profile for using OASIS DSS in Central Signing Services

### ISSUE THREAD

**Issue by martin-lindstrom** [swedenconnect/technical-framework#127]
The [Implementation Profile for using OASIS DSS in Central Signing Services](https://docs.swedenconnect.se/technical-framework/latest/07_-_Implementation_Profile_for_using_DSS_in_Central_Signing_Services.html) states that at least one `csig:Signer` element must be present in a signature request. This requirement makes it hard, or impossible, for use cases where a relying party asks a person that the RP has no prior knowledge about to sign something.

We need to analyze how we can relax these requirements so that we also support "anonymous" signing.

**Comment by GunnarKlintberg** [comment]
If you look at the CA responsibility from ETSI EN 319 411-1 it make sense to have csig:Signer
Element as a SHALL to be able to make sure to fulfill example requirement 
”• _REG-6.2.2-02: The TSP shall collect either direct evidence or an attestation from an appropriate and authorized source, of the identity (e.g. name) and if applicable, any specific attributes of subjects to whom a certificate is issued. Submitted evidence may be in the form of either paper or electronic documentation (in both cases the RA shall validate their authenticity). Verification of the subject's identity shall be at time of registration by appropriate means_.” 

That a Signature service can indirect via help of the e-service make sure that the solution fulfills that example user also accept the CA’s T&C and other requirement in this standard that is impossible to get if you do not has identify the end users identity in steps before the Sign service send the Authentication request to the IdP.
If you do not verify the end user identity in what-you-see-is-what-you-sign step and the step when the end user agree to send this data to the central sign service, requirement that the CA need to fulfill according to ETSI EN 319-411-1 will be almost impossible to implement in a both secure and understandable way. That are several other requirements in the ETSI standard that make sense to let the SP’s Signature service be responsible to collect so the CA can live up to the ETSI requirement when it issue the signee certificate.

**Comment by AndersTornqvist** [comment]
Is it possible for someone to explain what "anonymous" signing means? The identity of the Signer is known when the digital signature is computed. Does it not mean that the Signer is "initially anonymous"?

**Comment by martin-lindstrom** [comment]
> Is it possible for someone to explain what "anonymous" signing means? The identity of the Signer is known when the digital signature is computed. Does it not mean that the Signer is "initially anonymous"?

I am 100% that you understand what is meant. Especially when we write: "for use cases where a relying party asks a person that the RP has no prior knowledge about to sign something.".

**Comment by AndersTornqvist** [comment]
Just to be clear about: "for use cases where a relying party asks a person that the RP has no prior knowledge about to sign something." We assume that the "RP" is the Signature Service (Underskriftstjänst) which does not have the knowledge about the Signer initially? However, the Signer is known by the e-service and will later be known also to the Signature Service in order to create a signature. The business requirement is not regarding "anonymous" signing but to provide the Signer identity at a later stage ("just-in-time"). The proposed concept of "anonymous signing" is a contradiction and impossible to achieve.

**Comment by martin-lindstrom** [comment]
We will not use "anonymous" anywhere in the specs when/if we make an update ...

**Comment by AndersTornqvist** [comment]
It is good to avoid using “anonymous signing” which is an oxymoron and would confuse things when we consult our colleagues abroad.

So, the business requirement is to access the Signer details “just-in-time” when they are needed. If the Signer details are provided beforehand e.g. by signing into an application of the Authority, the Signature Service can compare the data and perform an agreed action if incorrect.

However, the Authority must in any case validate the signature of e.g. being by an eligible person. In some situations, additional data is required such as details and validity of a power of attorney. An Authority can use external services for technical digital signature validation but for other aspects it can be difficult to use external services or even allowed from legal point of view.

In some situations, the Signer details are not readily available and as this data is only used by the Signature Service, an Authority can decide to perform the required signature validation itself – which it must do anyway.
The step of a Signer approving Terms and Conditions should not be addressed in this context. Requirements to be addressed in this standard are those of Public Authorities in Sweden.  

Before DIGG was created the standardization body was “e-legitimationsnämnden” which handled the rules and process of standardization. In version 0.9 of October 14 2013 the <Signer> element was changed from “Required” to “Optional” after a very long discussion. The following clarification was also added: “If this element is present, then the signing service MUST verify that the authenticated identity of the signer is consistent with the attributes in this element.” If the <Signer> element is omitted, the signing service cannot perform this verification. But this omission does not in any way make the signature less secure.

The possible occurrence of the <Signer> element is not addressed by EN 319 411-1 and the quote is regarding the initial identity vetting of an end entity. The document that should address this issue is TS 119 432 “Protocols for remote digital signature creation” and the element here is <xs:element name="SignerIdentity" type="dss2:ClaimedIdentityType"/>. This is conditional and is only used in profile F for signing certificates list request. In the standardization work of the protocol we discussed in detail the Swedish requirement of the Signer element and one reason for its rejection was the SAML specificity. 
***
